# NUMPY

- stands for numerical python
- used for effectively storing, analysing and manipulating of data
- it is like list but too faster

In [2]:
import numpy as np

## Creation of array

### Creating array from list


In [3]:
arr_1d = np.array([1,2,3,4,5])
print(arr_1d)


arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])        #Here inner list is treated as row
print(arr_2d)


arr=np.array([range(i, i + 15,2) for i in [2, 4, 6]])
print(arr)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 2  4  6  8 10 12 14 16]
 [ 4  6  8 10 12 14 16 18]
 [ 6  8 10 12 14 16 18 20]]


### List vs numpy

In [4]:
py_list = [1,2,3]
print("Multiplication of list",py_list * 2)



np_array = np.array([1,2,3])   #element vise multiplication
print("Multiplication of array",np_array * 3)


import time                  # Also %timeout can use 
start = time.time()
py_list = [i*2 for i in range(1000000)]
print("\n List operation time", time.time() - start)

start = time.time()
np_array = np.arange(100000) *2 
print("\n Numpy operation time", time.time() - start)

Multiplication of list [1, 2, 3, 1, 2, 3]
Multiplication of array [3 6 9]

 List operation time 0.0886850357055664

 Numpy operation time 0.0016546249389648438


### Creating array from scratch

In [5]:
zeros_1 = np.zeros((3))
zeros_2 = np.zeros((4,3))

print(zeros_1)
print(zeros_2)

print("\n")

ones = np.ones((4,5))
print(ones)

print("\n")

full = np.full([4,5],5)
print(full)

print("\n")

sequence = np.arange(0,31,3)
print(sequence)

print("\n")

line = np.linspace(0, 1, 5)         # 5 is evenly spaced between 0 and 1
print(line)

print("\n")

random = np.random.random((4,3)) * 100
print(random)

print("\n")

rand = np.random.randint(0,10,(3,4))
print(rand)

print("\n")

iden = np.eye(4)
print(iden)

print("\n")

empty =  np.empty(4)
print(empty)

[0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]


[ 0  3  6  9 12 15 18 21 24 27 30]


[0.   0.25 0.5  0.75 1.  ]


[[77.16388765  9.33335407 53.57417772]
 [58.47440955 44.93708267 72.25243622]
 [45.63065422 62.25132332 46.4655354 ]
 [57.49877411 80.00572174 48.49063774]]


[[1 9 6 1]
 [1 8 5 1]
 [9 7 7 6]]


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


[1. 1. 1. 1.]


### Data types

- bool :-  Boolean (True or False) stored as a byte
- int32 :- Integer (–2147483648 to 2147483647)
- int64 :- Integer (–9223372036854775808 to 9223372036854775807)
- float32 :- Single-precision float: sign bit, 8 bits exponent, 23 bits mantissa
- float64 :- Double-precision float: sign bit, 11 bits exponent, 52 bits mantissa



In [6]:
print(np.array([1,2,3],dtype=float))

[1. 2. 3.]


---

## Basics of numpy array

### Attributes
- Determine size/shape/dimension/memory consuption & data type of array

In [7]:
np.random.seed(0)  # seed for reproducibility
x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(2, 3, 4))  # Three-dimensional array


print(x1)
print("\n")
print(x2)
print("\n")
print(x3)

print("\n")

print("Dimension:",x3.ndim)
print("Shape:",x3.shape)             #(@,)   @ = coloum
print("Size:",x3.size)               # give number of ele
print("Data type:",x3.dtype)
print("Item size:",x3.itemsize)

[5 0 3 3 7 9]


[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]


[[[8 1 5 9]
  [8 9 4 3]
  [0 3 5 0]]

 [[2 3 8 1]
  [3 3 3 7]
  [0 1 9 9]]]


Dimension: 3
Shape: (2, 3, 4)
Size: 24
Data type: int32
Item size: 4


### Indexing
- Getting and Setting value of individual ele

In [8]:
x = np.array([2,4,6,8,3,6,9])
print(x[0])
print(x[3])
print(x[-1])

print("\n")

y=np.array([[3, 5, 2, 4],[7, 6, 8, 8],[1, 6, 7, 7]])
print(y)
print(y[1,2])       # 1st row 2nd col
print(y[2,3])       # 2nd row 3rd col

y[1,2]=99           # can change individual ele
print(y)

2
8
9


[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
8
7
[[ 3  5  2  4]
 [ 7  6 99  8]
 [ 1  6  7  7]]


### Slicing

- Getting and Setting of subarray by main array

       x[start:stop:step]
       [R0:Rn:Rs,C0:Cn:Cs]

In [9]:
x= np.arange(11)
print(x[:5])
print(x[5:])
print(x[4:7])
print(x[::-1])      # reversed array

print("\n")

y=np.array([[3, 5, 2, 4],[7, 6, 8, 8],[1, 6, 7, 7]])
print(y)
print(y[:2,:2])
print(y[:3,::2])
print(y[::-1,::-1])
print(y[:,0])
print(y[1,:])       # ==y[1]

print("\n\n\n")
# it return view rather than copy i.e.,
# if we change something in array its subarray also changed

z = np.array([[12,5,2,4],[7,8,8,6],[1,6,7,7]])
z_subcpy = z[:2,:2].copy()
print(z_subcpy)
z_subcpy[0,0]=99
print(z_subcpy)
print(z)



[0 1 2 3 4]
[ 5  6  7  8  9 10]
[4 5 6]
[10  9  8  7  6  5  4  3  2  1  0]


[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
[[3 5]
 [7 6]]
[[3 2]
 [7 8]
 [1 7]]
[[7 7 6 1]
 [8 8 6 7]
 [4 2 5 3]]
[3 7 1]
[7 6 8 8]




[[12  5]
 [ 7  8]]
[[99  5]
 [ 7  8]]
[[12  5  2  4]
 [ 7  8  8  6]
 [ 1  6  7  7]]


### Reshaping
- Changing shape of array

In [10]:
grid = np.arange(1, 10).reshape((3, 3))
print(grid)
                                # Here no. of ele in range must be equal size
x = np.array([1,2,3,4,5,6])
print( x.reshape(2,3))

print("\n")

arr = np.arange(12)
print("Original Array:",arr)

reshaped = arr.reshape((3, 4))           #Reshape karenga 3-row,4-coloum me
print("\n Reshaped Array:\n",reshaped)


flattened = reshaped.flatten()          #2D array ko 1D me convert karenga
print("\n Flattened Array:",flattened)


ravaled = reshaped.ravel()              #It return view instead of copy (flattened copy return karta hai)
print("\n Ravaled Array:",ravaled)

transpose = reshaped.T
print("\n Transposed Array:\n",transpose)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]]


Original Array: [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Reshaped Array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 Flattened Array: [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Ravaled Array: [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Transposed Array:
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


### Joining
- Combining multiple arrays in one 

        axis=1 :- row / axis=0 :- coloum

In [11]:
x = np.array([1,2,3])
y = np.array([9,8,7])
z = np.array([11,22,33])
print(np.concatenate([x,y,z]))


print("\n")


original = np.array([[1,2],[3,4]])
new_row = np.array([[5,6]])
with_new_row = np.vstack((original, new_row))          #vstack add new row
print("Original:\n",original)
print("\n")
print("New row:\n",with_new_row)
print("\n")
new_col = np.array([[7],[8]])
with_new_col = np.hstack((original, new_col))          #hstack add new coloum
print("New coloum:\n",with_new_col)


print("\n")


y=np.array([[3, 5, 2, 4],[7, 6, 8, 8],[1, 6, 7, 7]])    # dstack for 3D array
x=np.array([[2,7,4,3],[8,9,6,4],[5,6,4,12]])
print(np.dstack([y,x]))

[ 1  2  3  9  8  7 11 22 33]


Original:
 [[1 2]
 [3 4]]


New row:
 [[1 2]
 [3 4]
 [5 6]]


New coloum:
 [[1 2 7]
 [3 4 8]]


[[[ 3  2]
  [ 5  7]
  [ 2  4]
  [ 4  3]]

 [[ 7  8]
  [ 6  9]
  [ 8  6]
  [ 8  4]]

 [[ 1  5]
  [ 6  6]
  [ 7  4]
  [ 7 12]]]


- Array Compatibility

In [12]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9])

print("Compatibility Shapes",a.shape==b.shape)      #use when to check shape is equal

Compatibility Shapes True


### Spliting
- Splitting one array in many

In [13]:
x = np.array([1,2,3,99,33,41,42,47])
x1,x2,x3 = np.split(x,[4,7])
print(x1,x2,x3)


print("\n")


grid = np.arange(1,17).reshape([4,4])
print(grid)
upper,lower = np.hsplit(grid ,[3])
print(upper)
print(lower)
upper,lower = np.vsplit(grid ,[3])
print(upper)
print(lower)

[ 1  2  3 99] [33 41 42] [47]


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]
 [13 14 15]]
[[ 4]
 [ 8]
 [12]
 [16]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[13 14 15 16]]


- Deletation of ele


In [14]:
arr = np.array([1,2,3,4,5])
deleted = np.delete(arr,2)
print("Array after deletation",deleted)

Array after deletation [1 2 4 5]


---

## Ufunction

- Ufunc in numpy is a function that operates element wise on array

### Arthmetic Operation

In [15]:
x = np.arange(11)
print(x)
print(np.add(x,3))
print(np.subtract(x,5))
print(np.multiply(x,5))
print(np.power(2,x))     # 2**x 
print(np.power(x,2))     # x**2
print("")
print(np.mod(x,2))       # x%2
print(np.mod(x,3))
print("")
print(np.floor_divide(x,2))
print(np.floor_divide(x,3))
print("")
print(np.abs(x))

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 3  4  5  6  7  8  9 10 11 12 13]
[-5 -4 -3 -2 -1  0  1  2  3  4  5]
[ 0  5 10 15 20 25 30 35 40 45 50]
[   1    2    4    8   16   32   64  128  256  512 1024]
[  0   1   4   9  16  25  36  49  64  81 100]

[0 1 0 1 0 1 0 1 0 1 0]
[0 1 2 0 1 2 0 1 2 0 1]

[0 0 1 1 2 2 3 3 4 4 5]
[0 0 0 1 1 1 2 2 2 3 3]

[ 0  1  2  3  4  5  6  7  8  9 10]


### Trigonometric Operation

In [16]:
theta = np.linspace(0,np.pi,3)        # This will give 0, half pie and pie
print(theta)
print("sin(0)=",(np.sin(theta)))
print("cos(0)=",(np.cos(theta)))
print("tan(0)=",(np.tan(theta)))

print()

x = [-1, 0, 1]
print("x         = ", x)
print("arcsin(x) = ", np.arcsin(x))
print("arccos(x) = ", np.arccos(x))
print("arctan(x) = ", np.arctan(x))

[0.         1.57079633 3.14159265]
sin(0)= [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(0)= [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(0)= [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]

x         =  [-1, 0, 1]
arcsin(x) =  [-1.57079633  0.          1.57079633]
arccos(x) =  [3.14159265 1.57079633 0.        ]
arctan(x) =  [-0.78539816  0.          0.78539816]


### Exp & Log Operation

In [17]:
x = [1, 2, 3]
print("x     =", x)
print("e^x   =", np.exp(x))
print("2^x   =", np.exp2(x))
print("3^x   =", np.power(3, x))

print("\n")

x = [1, 2, 4, 10]
print("x        =", x)
print("ln(x)    =", np.log(x))
print("log2(x)  =", np.log2(x))
print("log10(x) =", np.log10(x))

print("\n")

x = [0, 0.001, 0.01, 0.1]           #used when x is very small for precise calculation
print("exp(x) - 1 =", np.expm1(x))
print("log(1 + x) =", np.log1p(x))

x     = [1, 2, 3]
e^x   = [ 2.71828183  7.3890561  20.08553692]
2^x   = [2. 4. 8.]
3^x   = [ 3  9 27]


x        = [1, 2, 4, 10]
ln(x)    = [0.         0.69314718 1.38629436 2.30258509]
log2(x)  = [0.         1.         2.         3.32192809]
log10(x) = [0.         0.30103    0.60205999 1.        ]


exp(x) - 1 = [0.         0.0010005  0.01005017 0.10517092]
log(1 + x) = [0.         0.0009995  0.00995033 0.09531018]


- Inverse the value

In [18]:
values = np.random.randint(1, 10, size=5)
print(1.0/values)

[1.         0.2        0.125      0.25       0.33333333]


### Suming / minimum & maximum

In [19]:
np.random.seed(0)
A = np.random.random(100)
print(np.sum(A))

big_array = np.random.rand(1000000)
print(np.max(big_array))
print(np.sum(big_array))
print(np.min(big_array))
%timeit np.max(big_array)
%timeit max(big_array)

print("\n")

np.random.seed(0)
m = np.random.random((3,4))
n = np.random.random((3,4))
print(m)
print(np.sum(m))
print(np.prod(m))
print(np.mean(m))
print(np.median(m))
print(np.std(m))
print(np.var(m))
print(np.min(m))             # give min value of row or col
print(np.max(m))
print(np.max(m,axis=1))      # give max value across col  
print(np.max(m,axis=0))      # give min value across row
print(np.argmin(m))          # find index of min value
print(np.argmax(m))
print(np.percentile(m,25))
print(np.percentile(m,75))

47.279383951251766
0.9999997207656334
500385.08749075513
7.071203171893359e-07
604 μs ± 70.2 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
69.7 ms ± 1.95 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


[[0.5488135  0.71518937 0.60276338 0.54488318]
 [0.4236548  0.64589411 0.43758721 0.891773  ]
 [0.96366276 0.38344152 0.79172504 0.52889492]]
7.478282790980994
0.002129886612759326
0.6231902325817494
0.5757884399994844
0.17751915478163727
0.031513050314386885
0.3834415188257777
0.9636627605010293
[0.71518937 0.891773   0.96366276]
[0.96366276 0.71518937 0.79172504 0.891773  ]
9
8
0.5060679926303515
0.7343232842999807


---

## Broadcasting

- Operation of array of different size 

In [20]:
a = np.array([1,2,3])
b = np.array([5,5,5])
print(a+b)
print(a+10)             # Here we can think that 10 is stretches into [5,5,5]
b = np.arange(3)[:,np.newaxis]          # a=[0,1,2]   b=[[0]
                                        #                [1]
                                        #                [2]]
print(a+b)        

print("\n")

M = np.ones((2, 3))
a = np.arange(3)
print(a.shape)
print(a)
print(M.shape)
print(M+a)


a = np.arange(3).reshape((3,1))
b = np.arange(4)
print(b)
print(a)
print(a+b)

[6 7 8]
[11 12 13]
[[1 2 3]
 [2 3 4]
 [3 4 5]]


(3,)
[0 1 2]
(2, 3)
[[1. 2. 3.]
 [1. 2. 3.]]
[0 1 2 3]
[[0]
 [1]
 [2]]
[[0 1 2 3]
 [1 2 3 4]
 [2 3 4 5]]


### Rules
- Find shapes (*,#) if *1 = *2 or #1 = #2 sum is possible
- If single element [99] sum is possible by stretching in both row and col.
- Stay aware with 1D arry do it manually.

##  Comparisons, Masks, and Boolean Logic

### Boolean Logic

In [21]:
x = np.array([1,2,3,4,5])
print(x<3)
print(np.less(x,3))
print(x>3)
print(np.greater(x,3))
print(x!=3)
print(np.not_equal(3,x))
print(x==3)
print(np.equal(x,3))


print("\n")


np.random.seed(0)
rng = np.random.RandomState(0)
x = rng.randint(10,size=(3,4))
print(x)
print(np.greater_equal(x,3))
print(np.count_nonzero(x<6))
print(np.sum(x<6))
print(np.sum(x<6,axis=0))
print(np.any(x>3))
print(np.all(x>=0))  
print(np.all(x>=0,axis=1))  


print("\n")

a = np.array([1, 2, 3, 4, 5])
b = np.array([5, 4, 3, 2, 1])

print("np.logical_and(a > 2, b < 3):", np.bitwise_and(a > 2, b < 3))   # AND
print("np.logical_or(a > 2, b < 3):", np.logical_or(a > 2, b < 3))     # OR
print("np.logical_not(a > 2):", np.logical_not(a > 2))                 # NOT

print("Values in a where a > 2:",a[a > 2])

[ True  True False False False]
[ True  True False False False]
[False False False  True  True]
[False False False  True  True]
[ True  True False  True  True]
[ True  True False  True  True]
[False False  True False False]
[False False  True False False]


[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]
[[ True False  True  True]
 [ True  True  True  True]
 [False  True  True  True]]
8
8
[2 2 2 2]
True
True
[ True  True  True]


np.logical_and(a > 2, b < 3): [False False False  True  True]
np.logical_or(a > 2, b < 3): [False False  True  True  True]
np.logical_not(a > 2): [ True  True False False False]
Values in a where a > 2: [3 4 5]


### Mask and Fancy indexing

- Use Masking when filtering based on value or condition.
- Use Fancy Indexing when selecting specific positions or elements directly by index.

In [ ]:
arr = np.array([10, 20, 30, 40, 50])

# Create a mask where elements are greater than 25
mask = arr > 25
print(mask)           # [False False  True  True  True]

# Use mask to filter values
filtered = arr[mask]
print(filtered)       # [30 40 50]


print("\n")


matrix = np.array([[1, 5, 7],
                   [2, 6, 9],
                   [3, 4, 8]])

# Mask: values greater than 5
mask = matrix > 5
print(mask)

# Apply mask
print(matrix[mask])                 # Return 1D array with value of True condition


print("\n")


arr = np.array([1, 2, 3, 4, 5])

# Replace even numbers with 0
new_arr = np.where(arr % 2 == 0, 0, arr)
print(new_arr)  


[False False  True  True  True]
[30 40 50]


[[False False  True]
 [False  True  True]
 [False False  True]]
[7 6 9 8]


[1 0 3 0 5]


In [33]:
arr = np.array([10, 20, 30, 40, 50])

# Select elements at index 1, 3, and 4
idx = [1, 3, 4]
print(arr[idx])  


print("\n")


matrix = np.array([[11, 12], 
                   [21, 22], 
                   [31, 32]])

# Select rows at index 0 and 2
print(matrix[[0, 2]])  

print("\n")

arr = np.array([1, 2, 3, 4, 5])
arr[[0, 2, 4]] = 100                                # Change elements at index 0, 2, 4
print(arr)  # Output: [100 2 100 4 100]

print("\n")

matrix = np.array([[10, 20, 30],
                   [40, 50, 60],
                   [70, 80, 90]])

rows = [0, 1, 2]
cols = [1, 2, 0]

print(matrix[rows, cols])  # Output: [20 60 70]


[20 40 50]


[[11 12]
 [31 32]]


[100   2 100   4 100]


[20 60 70]


### Sorting


In [ ]:
unsorted = np.array([3,1,4,5,6,8,4,3,5,6,4])
print("Sorted Array",np.sort(unsorted))
print("Index of Sorted Array",np.argsort(unsorted))
print(np.partition(unsorted,6))
arr_2d_unsorted = np.array([[3,4],[1,2],[2,3]])
print("Sorted 2D array by coloumn",np.sort(arr_2d_unsorted,axis=0))


print("\n")


rand = np.random.RandomState(42)
X = rand.randint(0, 10, (4, 6))
print(X)
print("\n")
print(np.sort(X,axis=0))
print(np.sort(X,axis=1))
print("\n")
print(np.partition(X, 2, axis=1))           # Elements before it are smaller (in any order)
print(np.argpartition(X, 2, axis=1))        #    and elements after it are larger.

Sorted Array [1 3 3 4 4 4 5 5 6 6 8]
Index of Sorted Array [ 1  0  7  2  6 10  8  3  9  4  5]
[1 3 3 4 4 4 5 5 6 6 8]
Sorted 2D array by coloumn [[1 2]
 [2 3]
 [3 4]]


[[6 3 7 4 6 9]
 [2 6 7 4 3 7]
 [7 2 5 4 1 7]
 [5 1 4 0 9 5]]


[[2 1 4 0 1 5]
 [5 2 5 4 3 7]
 [6 3 7 4 6 7]
 [7 6 7 4 9 9]]
[[3 4 6 6 7 9]
 [2 3 4 6 7 7]
 [1 2 4 5 7 7]
 [0 1 4 5 5 9]]


[[3 4 6 6 7 9]
 [2 3 4 6 7 7]
 [1 2 4 5 7 7]
 [0 1 4 5 5 9]]
[[1 3 0 4 2 5]
 [0 4 3 1 2 5]
 [4 1 3 2 0 5]
 [3 1 2 0 5 4]]


### Structured Data

In [47]:
# data = np.zeros(4, dtype={'names': ('name', 'age', 'weight'),
#                           'formats': ('U10', 'i4', 'f8')})




dt=np.dtype([('name', 'U10'), ('age', 'i4'), ('weight', 'f8')])
data = np.zeros(4, dtype=dt)



print(data.dtype)
data[0] = ('Ayush', 19, 50)
data[1] = ('Ravi', 21, 60)
data[3] = ('Laxmi',18,43)
print(data)

print(data['name'])
print(data[3])

data[data['age']>18]['name']


[('name', '<U10'), ('age', '<i4'), ('weight', '<f8')]
[('Ayush', 19, 50.) ('Ravi', 21, 60.) ('',  0,  0.) ('Laxmi', 18, 43.)]
['Ayush' 'Ravi' '' 'Laxmi']
('Laxmi', 18, 43.0)


array(['Ayush', 'Ravi'], dtype='<U10')

In [46]:
data = np.array([
    ('Ayush', 19, 50.0),
    ('Ravi', 21, 60.0),
    ('Laxmi', 18, 43.0),
], dtype=[('name', 'U10'), ('age', 'i4'), ('weight', 'f8')])
print(data)

[('Ayush', 19, 50.) ('Ravi', 21, 60.) ('Laxmi', 18, 43.)]
